### ISSUE TITLE
我做了一个Hexo版本的zozo主题

### ISSUE THREAD

**Issue by MyFaith** [varkai/hugo-theme-zozo#1]
非常喜欢这个主题风格，由于使用Hexo，所以自己写了一个版本。[链接](https://github.com/MyFaith/hexo-theme-zozo)
目前正在开发中，做了一些微调，并在如下标注的来源，不知是否介意。😂
![image](https://user-images.githubusercontent.com/8826441/56506970-87b4af80-6552-11e9-9206-98558ef305bc.png)
![image](https://user-images.githubusercontent.com/8826441/56506993-93a07180-6552-11e9-996b-67bf2d276e37.png)

**Comment by varkai** [comment]
> 非常喜欢这个主题风格，由于使用Hexo，所以自己写了一个版本。[链接](https://github.com/MyFaith/hexo-theme-zozo)
> 目前正在开发中，做了一些微调，并在如下标注的来源，不知是否介意。😂
> ![image](https://user-images.githubusercontent.com/8826441/56506970-87b4af80-6552-11e9-9206-98558ef305bc.png)
> ![image](https://user-images.githubusercontent.com/8826441/56506993-93a07180-6552-11e9-996b-67bf2d276e37.png)

没问题👌

**Comment by MyFaith** [comment]
好的，感谢！
