### ISSUE TITLE
文章渲染的段间距是否可以调整一下？

### ISSUE THREAD

**Issue by ibrights** [varkai/hugo-theme-zozo#11]
markdown文档渲染出来之后，段间距与行间距一致，导致段落与段落之间没有明确区分。因此文章渲染出来之后，看起来有一种所有文字堆砌在一起的感觉，不太美观。建议调整一下文章的段间距。

**Comment by varkai** [comment]
> markdown文档渲染出来之后，段间距与行间距一致，导致段落与段落之间没有明确区分。因此文章渲染出来之后，看起来有一种所有文字堆砌在一起的感觉，不太美观。建议调整一下文章的段间距。

已调整
