### ISSUE TITLE
Cannot hide post with `hidden: true`

### ISSUE THREAD

**Issue by mfirhas** [varkai/hugo-theme-zozo#13]
I'm experimenting with this theme. When I tried to hide a post it didn't work. 

Expected: the post is hidden in the list and archive.
Actual: the post keep showing normally.

Hugo Version: v0.74.3/extended darwin/amd64
OS: System Version: macOS 10.15.6

**Comment by varkai** [comment]
I 'm sorry, The hidden function has been removed some time ago. I forgot to update the instruction document.

**Comment by mfirhas** [comment]
Thanks for the response. Would you like to consider this [PR](https://github.com/varkai/hugo-theme-zozo/pull/14). Thanks!

**Comment by varkai** [comment]
> Thanks for the response. Would you like to consider this [PR](https://github.com/varkai/hugo-theme-zozo/pull/14). Thanks!
`Draft`，It seems that the system has its own judgment, and there is no need to add additional judgment.

**Comment by mfirhas** [comment]
I don't get what you say. If you can't accept the PR, just close it. Thank you.
