### ISSUE TITLE
新增内容

### ISSUE THREAD

**Issue by bugxch** [varkai/hugo-theme-zozo#15]
页面很喜欢，不过能不能再添加一些内容：
1. 文章加上统计数字，共××字；
2. 代码是否可以自己加上行数；
3. 每个文章是否可以设置toc目录

谢谢

**Comment by varkai** [comment]
> 页面很喜欢，不过能不能再添加一些内容：
> 
> 1. 文章加上统计数字，共××字；
> 2. 代码是否可以自己加上行数；
> 3. 每个文章是否可以设置toc目录
> 
> 谢谢
暂时没有这方面的打算，因为本身主题主打简洁，所以不会去添加很多其他信息，如果有需要，可能需要您自己fork修改了，抱歉。
