### ISSUE TITLE
似乎不支持自动生成文章目录？

### ISSUE THREAD

**Issue by BytePrince** [varkai/hugo-theme-zozo#17]
个人感觉这个还是蛮重要的额，尤其是篇幅较长的文章，很需要一个目录以供快速跳转

**Comment by varkai** [comment]
> 个人感觉这个还是蛮重要的额，尤其是篇幅较长的文章，很需要一个目录以供快速跳转

这个您可以自己添加，因为这个主题尽量的简洁，尽量剔除一些不必要的东西。
