### ISSUE TITLE
有两个问题样式问题

### ISSUE THREAD

**Issue by malinkang** [varkai/hugo-theme-zozo#2]
主题很漂亮已经用上了，目前有两个样式问题，希望作者能够修正一下，非常感谢。
1、当使用disqus的时候宽度铺满了整个屏幕，希望能和菩提树下的样式一致。具体问题可以看我的博客：https://malinkang.cn/2019/android-handler/ 

或者下图所示：

![image](https://user-images.githubusercontent.com/3365208/57568539-56295880-741b-11e9-971e-c7bba4a2606b.png)

**Comment by wtser** [comment]
我 fork 了一份，调整了你说的第一个问题
https://github.com/wtser/hugo-theme-zozo

demo
http://blog.wtser.com/posts/%E7%BB%93%E5%90%88-css3-transition-transform-%E5%AE%9E%E7%8E%B0%E7%AE%80%E5%8D%95%E7%9A%84%E8%B7%91%E9%A9%AC%E7%81%AF%E6%95%88%E6%9E%9C/

**Comment by varkai** [comment]
已修正
