### ISSUE TITLE
大佬，可否增加搜索功能呢。

### ISSUE THREAD

**Issue by huanauh** [varkai/hugo-theme-zozo#4]
大佬，可否增加搜索功能呢？个人觉得还是很有必要的。

**Comment by rewired-gh** [comment]
同求。

不过文章少的话意义不大，文章多的话静态页面的实现方式性能不好（不过总好过没有）。
目前建议自己修改主题，根据需求加入搜索功能。

**Comment by wedojava** [comment]
同求

我实现了这个： https://gist.github.com/cmod/5410eae147e4318164258742dd053993  
但是有些不完美，我比他的漂亮，但是我的报错了，目前还没解决。好久没搞 js 了，搞不定啊。
https://wedojava.gitee.io

**Comment by varkai** [comment]
暂时没有计划哦
