### ISSUE TITLE
首页不显示文章是哪里设置有问题？

### ISSUE THREAD

**Issue by GuoRan18** [varkai/hugo-theme-zozo#5]
大佬，请问首页不显示文章是哪里设置有问题？

**Comment by fatrbaby** [comment]
同样的问题，正在找原因。

**Comment by GuoRan18** [comment]
> 同样的问题，正在找原因。

我之前是用的腾讯云开发者平台试的会出现这个问题，用vps就没这个问题了。

**Comment by fatrbaby** [comment]
> > 同样的问题，正在找原因。
> 
> 我之前是用的腾讯云开发者平台试的会出现这个问题，用vps就没这个问题了。

可能和hugo的版本有关。我本地以前是正确的。

**Comment by jiaoshijie** [comment]
好像把这个文件/layouts/partials/post.html第一行的
       {{ $pages := where .Pages "Params.hidden" "ne" true }}
改成
      {{ $pages := where .Site.RegularPages "Params.hidden" "ne" true }}

首页显示就正常了

**Comment by jiangfangzheng** [comment]
hugo 0.57.2更新中提到从0.58开始.Page的行为有变更，具体参见：https://github.com/gohugoio/hugo/releases/tag/v0.57.2

**Comment by malinkang** [comment]
这个库怎么不更新了。

**Comment by scopor** [comment]
新生成的文章中的 draft 的值改成 false 就可以了

**Comment by varkai** [comment]
已修正
