### ISSUE TITLE
不应该使用“△”作为“返回顶部”的符号

### ISSUE THREAD

**Issue by rewired-gh** [varkai/hugo-theme-zozo#6]
原因：在许多字体中，这个符号都不能表达此意思。此外，还不符合整体设计风格。

建议修改方式：
1. 使用矢量图；
2. 使用“↑”符号；

希望作者的主题越做越好！

**Comment by rewired-gh** [comment]
此外，请问一下作者接受 PR 吗？我愿意贡献一些我的代码。

**Comment by varkai** [comment]
> 原因：在许多字体中，这个符号都不能表达此意思。此外，还不符合整体设计风格。
> 
> 建议修改方式：
> 
> 1. 使用矢量图；
> 2. 使用“↑”符号；
> 
> 希望作者的主题越做越好！

谢谢您的建议，已经采用svg替换了
