### ISSUE TITLE
table样式不生效

### ISSUE THREAD

**Issue by Yellowpal** [varkai/hugo-theme-zozo#7]
问题：markdown 中的table标签样式显示有问题，zozo.css中定义的table样式不生效。
解决方法：将zozo.css中table相关的样式定义前面加上.markdown

**Comment by varkai** [comment]
> 问题：markdown 中的table标签样式显示有问题，zozo.css中定义的table样式不生效。
> 解决方法：将zozo.css中table相关的样式定义前面加上.markdown
不会吧，我的demo上显示是正常的啊：https://zozo.varkai.com/posts/theme-preview/

**Comment by Yellowpal** [comment]
> > 问题：markdown 中的table标签样式显示有问题，zozo.css中定义的table样式不生效。
> > 解决方法：将zozo.css中table相关的样式定义前面加上.markdown
> > 不会吧，我的demo上显示是正常的啊：https://zozo.varkai.com/posts/theme-preview/

应该是我用的是以前旧版本的问题，拉了新的代码就没问题了，谢谢
